### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by webmastak** [denandz/GLORP#1]
I launch GLORP, go to the Replay tab, enter the host, port, use TLS, press the Go button and nothing happens ...
I have not installed squid. GLORP won't work without it?

**Comment by denandz** [comment]
You dont need squid, you need a replay item to modify. Try sending a request to glorp with `curl -x http://127.0.0.1:8080 example.com` and then sending that to the replayer with ctrl-r. 

Commit b55423ac6379a976776d3855a5414392cb9abd36 adds the ability to create blank replays to build requests from scratch. You can do this with ctrl-b. 

Closing this issue

**Comment by webmastak** [comment]
If you send a request via curl, then everything works as it should.
If in the tabs Replay -> Ctrl + b then it gives an error.
![eroor](https://i.imgur.com/esfjXxU.png)
